### ISSUE TITLE
installing the repo

### ISSUE THREAD

**Issue by otmaneelhaddaji** [MohamedSalahApdElzaher/Advanced_MultiVendor_eCommerce#1]
HI salah can you please tell me to start a server for the repo

**Comment by MohamedSalahApdElzaher** [comment]
hi there, this repo is not finished yet, I still working on it for learning purposes
I use localhost, you need to clone the repo `git clone`, put it in your server root folder, configure the database, and finally run the command `composer install` 
for migration and dummy data use command `php artisan migrate:fresh --seed`
after that start your server and run command `php artisan serve`
hope that helps

**Comment by otmaneelhaddaji** [comment]
Thank u that will help a lot
